version: '3.0'
services:
  webserver:
    build: .
    ports:
      - "80:80"
    links:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: redcorona
      MYSQL_USER: redcorona
      MYSQL_PASSWORD: redcorona111!
      MYSQL_ROOT_PASSWORD: rootroot(_)!@
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    networks:
      - default