services:
  bot_service:
    build:
      context: ./bot
      dockerfile: Dockerfile
      args:
        BASE_URL: "http://challenge_service:9222"
    volumes:
      - ./bot:/app
      - /app/node_modules
    expose:
      - "3000"
    networks:
      - internal
    depends_on:
      - challenge_service

  challenge_service:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        BOT_URL: "http://bot_service:3000"
    ports:
      - "9222:9222"
    volumes:
      - ./server:/app
    networks:
      - internal

networks:
  internal:
    driver: bridge
