accounts:
  - name: owner
    balance: 100ether
  - name: user
    balance: 100ether

deployments:
  - name: level_contract
    path: "./src/Contract.sol:Level"
    private_key: owner_private_key # Use the private key of owner

# These values will be exposed to the player
exposed:
  - level_contract_address
  - user_private_key
  - user_address

verifier: "python /app/verifier.py"
flag_path: /app/flag.txt