accounts:
  - name: owner
    balance: 10ether
  - name: user
    balance: 10ether

deployments:
  - name: level_contract
    path: "./src/Challenge.sol:Challenge"
    private_key: owner_private_key
    constructor_args:
      - "0"
      - "--optimize"
      - "--via-ir"

exposed:
  - level_contract_address
  - user_private_key
  - user_address

verifier: "python /app/verifier.py"
flag_path: /app/flag.txt
