apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag
  namespace: flag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag
  template:
    metadata:
      labels:
        app: flag
    spec:
      containers:
      - name: flag
        image: busybox
        command:
        - busybox
        - tail
        - -f
        - /dev/null
        volumeMounts:
        - name: flag
          mountPath: /etc/flag
          subPath: flag
      volumes:
      - secret:
          secretName: flag
        name: flag
---
apiVersion: v1
kind: Secret
metadata:
  name: flag
  namespace: flag
stringData:
  flag: "<SECRET>"

