apiVersion: v1
kind: Pod
metadata:
  name: vm
  labels:
    app: vm
spec:
  serviceAccountName: pod-manager
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sh", "-c", "tail -f /dev/null"]
    ports:
    - containerPort: 22
  restartPolicy: OnFailure

